version: '3.4'

services:
  recipebook.api:
    image: ${DOCKER_REGISTRY-}recipebookapi
    build:
      context: .
      dockerfile: RecipeBook.Api/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081
    # depends_on:
    #   - recipebook.db
